- name: Deploy Slack Bot In Local
  connection: ssh
  gather_facts: false
  hosts: localhost
  vars:
    repo_folder: ~/www/github-deployment/repos/
    bundle_file: ~/www/github-deployment/repos/bundle.zip
    live_folder: ~/www/slack-pm2-proxy/build

  tasks:
    - git:
        repo: git@github.com:purple-seal/slack-pm2-proxy.git
        dest: "{{ repo_folder }}"
        update: yes
        force: yes
    
    - name: Install dev dependencies
      npm:
        path: "{{ repo_folder }}"

    - name: Zip all files
      archive:
        path:
        - "{{ repo_forder }}"
        exclude_path:
        - "{{ repo_forder }}/node_modules"
        dest: "{{ bundle_file }}"
        format: zip

    - name: Copy build to live directory
      command: cp {{ bundle_file }} {{ live_folder }}

    - name: Unzip bundle
      unarchive:
        src: "{{ live_folder }}/bundle.zip"
        dest: "{{ live_folder }}"

    - name: Install dependencies
      npm:
        path: "{{ live_folder }}"    
