- name: Deploy Slack Bot In Local
  connection: ssh
  gather_facts: false
  hosts: localhost
  vars:
    repo_folder: ~/www/github-deployment/repos/
    bundle_file: bundle.zip
    live_folder: ~/www/slack-pm2-proxy/build

  tasks:
    - git:
        repo: git@github.com:purple-seal/slack-pm2-proxy.git
        dest: "{{ repo_folder }}"
        update: yes
        force: yes
    
    - name: Install dev dependencies
      npm:
        path: "{{ repo_folder }}"

    - name: Zip all files
      archive:
        path:
        - "{{ repo_folder }}"
        exclude_path:
        - "{{ repo_folder }}/node_modules"
        dest: "{{repo_folder}}/{{ bundle_file }}"
        format: zip

    - name: Create build directory
      file:
        path: "{{ live_folder }}"
        state: directory
        recurse: yes
      
    - name: Copy build to live directory
      copy: 
        src: "{{repo_folder}}/{{ bundle_file }}"
        dest: "{{ live_folder }}/{{ bundle_file }}"

    - name: Unzip bundle
      unarchive:
        src: "{{ live_folder }}/{{ bundle_file }}"
        dest: "{{ live_folder }}"

    - name: Install dependencies
      npm:
        path: "{{ live_folder }}"    
